version: "3.8"
services:
  jobmanager:
    image: flink:latest
    ports:
      - "64000:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
      replicas: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 2g
        taskmanager.numberOfTaskSlots: 5
    volumes:
      - ./data:/data
